### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by russellb** [nexodus-io/nexodus#428]
We bootstrapped this project within `redhat-et`, but as the project grows, it should be moved to a neutral project-specific home. We should create a github org, move the repo there, and fix all the fallout.

See #440 for details on the proposed move and new project naming.

Tasks:

- [x] Decide on new names - see #442 (@russellb)
- [x] Register `nexodus-io` github org (@russellb)
- [x] Purchase `nexodus.io` domain (@russellb)
- [x] Move repo to github.com/nexodus-io/nexodus (@russellb)
- [x] Update github path references in code and docs to the new path (@russellb) #502 
- [x] Rename binaries according to #440 (@russellb) #502
- [x] Fix e2e test code to reflect new binary names (@nerdalert) #510
- [x] Rename COPR rpm repository (@russellb)
- [x] Rename rpm files, fix rpm contents, build, and publishing (@russellb)
- [x] Rename container image repos (@vishnoianil )
- [x] Fix container image building and publishing (@vishnoianil )
- [x] Create new aws bucket for nexodus-io and fix CI to push binaries to it (@vishnoianil )
- [x] Fix other CI fallout (@vishnoianil @nerdalert )
- [x] Migrate docs to use the new names from #440 (@russellb) #509
- [x] Change the remaining apex references throughout the code
- [x] Setup quay.io organization for pushing nexodus related images (@vishnoianil )
- [x] Migrate ROSA deployment to nexodus.io (@vishnoianil )
- [x] Replace the logo #513
- [x] Fix apex references in the UI (@nerdalert) #514

**Comment by russellb** [comment]
I propose doing this right after merging #345, since we expect things to break for a bit then anyway.
